#!/usr/bin/env node

/**
 * scripts/docs-serve.mjs — Serve the docs/ directory locally to browse the
 * user guide with its screenshots.
 *
 *   npm run docs:serve
 *
 * The guide itself (docs/user-guide.md) is hand-maintained; screenshots are
 * (re)generated by `npm run docs:capture` (scripts/docs-capture.mjs).
 */

import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_DIR = path.join(__dirname, '..', 'docs');
const PORT = 5174;

const MIME = {
  '.md': 'text/markdown; charset=utf-8',
  '.png': 'image/png',
  '.html': 'text/html; charset=utf-8',
};

// Minimal markdown renderer for headings/lists/images/tables (guide browsing
// convenience only — GitHub renders the real thing).
function renderMarkdown(md) {
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const lines = esc(md).split('\n');
  const out = [];
  let inTable = false;
  for (const line of lines) {
    let m;
    if ((m = line.match(/^(#{1,6}) (.*)$/))) {
      out.push(`<h${m[1].length}>${m[2]}</h${m[1].length}>`);
    } else if ((m = line.match(/^!\[(.*)\]\((.*)\)$/))) {
      out.push(`<figure><img src="${m[2]}" alt="${m[1]}" style="max-width:100%"><figcaption>${m[1]}</figcaption></figure>`);
    } else if ((m = line.match(/^\|(.+)\|$/))) {
      const cells = m[1].split('|').map((c) => c.trim());
      if (cells.every((c) => /^-+$/.test(c) || c === '')) continue; // separator
      const tag = inTable ? 'td' : 'th';
      out.push(`<tr>${cells.map((c) => `<${tag}>${c}</${tag}>`).join('')}</tr>`);
      inTable = true;
      continue;
    } else {
      if (inTable) { out.push('</table>'); inTable = false; }
      if ((m = line.match(/^- (.*)$/))) {
        out.push(`<li>${m[1]}</li>`);
      } else if (line.trim() === '') {
        out.push('');
      } else {
        out.push(`<p>${line}</p>`);
      }
    }
  }
  if (inTable) out.push('</table>');
  // consecutive <li> wrapping
  const html = out
    .join('\n')
    .replace(/(?:<li>.*<\/li>\n?)+/g, (mli) => `<ul>${mli}</ul>`)
    .replace(/(?:<tr>.*<\/tr>\n?)+(?=<)/g, (mt) => `<table>${mt}</table>`);
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>MediaPlan — Guide utilisateur</title>
<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:24px auto;padding:0 16px;line-height:1.5}
img{border:1px solid #ddd;border-radius:6px}figure{margin:12px 0}figcaption{font-size:12px;color:#666}
table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:4px 8px}</style></head>
<body>${html}</body></html>`;
}

const server = http.createServer((req, res) => {
  let file = req.url === '/' ? '/user-guide.md' : req.url;
  const full = path.join(DOCS_DIR, path.normalize(file).replace(/^(\.\.[/\\])+/, ''));
  if (!fs.existsSync(full)) {
    res.writeHead(404).end('Not found');
    return;
  }
  const ext = path.extname(full);
  if (ext === '.md') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(renderMarkdown(fs.readFileSync(full, 'utf-8')));
  } else {
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(fs.readFileSync(full));
  }
});

server.listen(PORT, () => {
  console.log(`📖 Guide utilisateur : http://localhost:${PORT}/`);
  console.log('   (captures régénérables via npm run docs:capture)');
});
